using Postgrest.Attributes;
using Postgrest.Models;
using UnityEngine.Scripting;

[Preserve]
[Table("profiles")]
public class Profile : BaseModel
{
    [PrimaryKey("id", false)]
    public string Id { get; set; }

    [Column("username")]
    public string Username { get; set; }
    
    // updated_at is auto-generated by database DEFAULT now()
}

[Preserve]
[Table("user_secrets")]
public class UserSecret : BaseModel
{
    [PrimaryKey("id", false)]
    public string Id { get; set; }

    [Column("email")]
    public string Email { get; set; }
    
    // created_at is auto-generated by database DEFAULT now()
}

[Preserve]
[Table("posts")]
public class Post : BaseModel
{
    [PrimaryKey("id", false)]
    public string Id { get; set; }

    [Column("author_id")]
    public string AuthorId { get; set; }

    [Column("content_text")]
    public string ContentText { get; set; }

    [Column("media_url")]
    public string MediaUrl { get; set; }

    [Column("media_type")]
    public string MediaType { get; set; }
    
    // created_at is auto-generated by database DEFAULT now()
}

[Preserve]
[Table("friendships")]
public class Friendship : BaseModel
{
    [PrimaryKey("id", false)]
    public long Id { get; set; }

    [Column("user_id")]
    public string UserId { get; set; }

    [Column("friend_id")]
    public string FriendId { get; set; }

    [Column("nickname")]
    public string Nickname { get; set; }
    
    // created_at is auto-generated by database DEFAULT now()
}

[Preserve]
[Table("read_receipts")]
public class ReadReceipt : BaseModel
{
    [Column("user_id")]
    public string UserId { get; set; }

    [Column("post_id")]
    public string PostId { get; set; }
    
    // opened_at is auto-generated by database DEFAULT now(), so we don't include it in inserts
}

[Preserve]
[Table("system_notifications")]
public class SystemNotification : BaseModel
{
    [PrimaryKey("id", false)]
    public string Id { get; set; }

    [Column("recipient_id")]
    public string RecipientId { get; set; }

    [Column("type")]
    public string Type { get; set; }

    [Column("content")]
    public string Content { get; set; }

    [Column("media_url")]
    public string MediaUrl { get; set; }

    [Column("media_type")]
    public string MediaType { get; set; }

    [Column("is_read")]
    public bool IsRead { get; set; }
    
    // created_at is auto-generated by database DEFAULT now()
}
